DROP TABLE VECTOR.STOCK;

DROP TABLE VECTOR.REVIEWS_VS;

DROP TABLE VECTOR.REVIEWS;

DROP TABLE VECTOR.PRODUCTS;

CREATE TABLE VECTOR.PRODUCTS (
    PROD_ID NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ),
    NAME VARCHAR2 (128),
    CATEGORY VARCHAR2 (128)
);

--DROP INDEX VECTOR.PRODUCTS;
CREATE UNIQUE INDEX "VECTOR"."PRODUCTS_PK" ON "VECTOR"."PRODUCTS" ("PROD_ID");

ALTER TABLE VECTOR.PRODUCTS ADD CONSTRAINT PRODUCTS_PK PRIMARY KEY ( PROD_ID ) USING INDEX LOGGING;

--DROP INDEX "VECTOR"."REVIEWS_PK";
CREATE TABLE VECTOR.REVIEWS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ),
    PROD_ID NUMBER,
    NAME VARCHAR2 (128),
    RATING NUMBER,
    CATEGORY VARCHAR2 (128),
    DESCRIPTION VARCHAR2 (4000),
    EMBEDDING VECTOR
);

CREATE UNIQUE INDEX "VECTOR"."REVIEWS_PK" ON "VECTOR"."REVIEWS" ("ID");

ALTER TABLE VECTOR.REVIEWS ADD CONSTRAINT REVIEWS_PK PRIMARY KEY ( ID ) USING INDEX LOGGING;

ALTER TABLE VECTOR.REVIEWS ADD CONSTRAINT PROD_ID_FK FOREIGN KEY ( PROD_ID ) REFERENCES VECTOR.PRODUCTS ( PROD_ID ) ON DELETE CASCADE NOT DEFERRABLE NOVALIDATE;

--DROP INDEX VECTOR.IDX_VS_DOCID;
CREATE TABLE "VECTOR"."REVIEWS_VS" (
    ID NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ),
    "DOCUMENT_ID" NUMBER,
    "DOCUMENT_NAME" VARCHAR2(512),
    "TEXT" CLOB COLLATE "USING_NLS_COMP",
    "METADATA" CLOB COLLATE "USING_NLS_COMP",
    "EMBEDDING" VECTOR,
    "EMBEDDING_MODEL" VARCHAR2(512)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE INDEX VECTOR.IDX_VS_DOCID ON VECTOR.REVIEWS_VS
    (
     DOCUMENT_ID ASC
    );

--DROP INDEX REVIEWS_VS_IVF_IDX;
CREATE VECTOR INDEX REVIEWS_VS_IVF_IDX ON REVIEWS_VS (EMBEDDING) ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;

CREATE TABLE VECTOR.STOCK (
    PROD_ID NUMBER,
    ITEM_NAME VARCHAR2 (128),
    CATEGORY VARCHAR2(128),
    LOCATION VARCHAR2 (128),
    STOCK INTEGER,
    RESTOCK_DATE DATE
) LOGGING;

ALTER TABLE VECTOR.STOCK ADD CONSTRAINT STOCK_PK PRIMARY KEY ( PROD_ID, LOCATION ) USING INDEX LOGGING;

ALTER TABLE VECTOR.STOCK ADD CONSTRAINT STOCK_PROD_ID_FK FOREIGN KEY ( PROD_ID ) REFERENCES VECTOR.PRODUCTS ( PROD_ID ) ON DELETE CASCADE NOT DEFERRABLE NOVALIDATE;