TRUNCATE TABLE REVIEWS_VS;

TRUNCATE TABLE REVIEWS;

TRUNCATE TABLE STOCK;

TRUNCATE TABLE PRODUCTS;

INSERT INTO PRODUCTS (
    NAME,
    CATEGORY
)
    SELECT
        DISTINCT NAME,
        CATEGORY
    FROM
        SCOTCH_REVIEWS;

INSERT INTO REVIEWS (
    PROD_ID,
    NAME,
    RATING,
    CATEGORY,
    DESCRIPTION
)
    SELECT
        DISTINCT P.PROD_ID      AS PROD_ID,
        SR.NAME,
        SR.RATING,
        SR.CATEGORY,
        SR.DESCRIPTION
    FROM
        SCOTCH_REVIEWS SR,
        PRODUCTS       P
    WHERE
        SR.NAME = P.NAME;

INSERT INTO STOCK (
    PROD_ID,
    ITEM_NAME,
    CATEGORY,
    LOCATION,
    STOCK,
    RESTOCK_DATE
)
    SELECT
        DISTINCT P.PROD_ID                                 AS PROD_ID,
        P.NAME                                    AS ITEM_NAME,
        P.CATEGORY                                AS CATEGORY,
        'online'                                  AS LOCATION,
        TRUNC(DBMS_RANDOM.VALUE(0, 20))           AS STOCK,
        SYSDATE + TRUNC(DBMS_RANDOM.VALUE(0, 21)) AS RESTOCK_DATE
    FROM
        PRODUCTS P
    ORDER BY
        DBMS_RANDOM.RANDOM FETCH FIRST 300 ROWS ONLY;

COMMIT;