-- USER SQL
CREATE USER VECTOR IDENTIFIED BY mrp@GHD0act7afb@ruc;

-- ADD ROLES
GRANT CONNECT TO VECTOR;
GRANT CONSOLE_DEVELOPER TO VECTOR;
GRANT DB_DEVELOPER_ROLE TO VECTOR;
GRANT DWROLE TO VECTOR;
GRANT OML_DEVELOPER TO VECTOR;
GRANT RESOURCE TO VECTOR;
ALTER USER VECTOR DEFAULT ROLE CONSOLE_DEVELOPER,DB_DEVELOPER_ROLE,DWROLE,OML_DEVELOPER;

-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'VECTOR',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'vector',
        p_auto_rest_auth=> TRUE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => 'VECTOR',
            ENABLED => TRUE
    );
    commit;
END;
/

-- ENABLE OML
ALTER USER VECTOR GRANT CONNECT THROUGH OML$PROXY;

-- QUOTA
ALTER USER VECTOR QUOTA UNLIMITED ON DATA;