SELECT
	DBMS_VECTOR.UTL_TO_EMBEDDING('hello', JSON('{"provider":"database", "model":"ALL_MPNET_BASE"}'))
FROM
	DUAL;

SELECT
	VECTOR_EMBEDDING(ALL_MPNET_BASE USING 'hello' AS DATA) AS EMBEDDING
FROM
	DUAL;

SELECT
	VS.*
FROM
	REVIEWS_VS VS
ORDER BY
	VECTOR_DISTANCE( VS.EMBEDDING, VECTOR_EMBEDDING(ALL_MPNET_BASE USING 'vanilla and fruit' AS DATA), COSINE) FETCH FIRST 10 ROWS ONLY;

-- withput vector index
SELECT
	VS.*
FROM
	REVIEWS_VS VS
ORDER BY
	VECTOR_DISTANCE( VS.EMBEDDING, (
		SELECT
			X.EMBEDDING
		FROM
			REVIEWS_VS X
		WHERE
			X.DOCUMENT_ID = 1023
	), COSINE) FETCH FIRST 10 ROWS ONLY;

-- using vector index
SELECT
	VS.*
FROM
	REVIEWS_VS VS
ORDER BY
	VECTOR_DISTANCE( VS.EMBEDDING, (
		SELECT
			X.EMBEDDING
		FROM
			REVIEWS_VS X
		WHERE
			X.DOCUMENT_ID = 1023
	), COSINE) FETCH APPROXIMATE FIRST 10 ROWS ONLY WITH TARGET ACCURACY 95;