DROP TABLE "VECTOR"."REVIEWS";

CREATE TABLE "VECTOR"."REVIEWS" (
    "ID" NUMBER,
    "NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "CATEGORY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "RATING" NUMBER,
    "PRICE" NUMBER,
    "CURRENCY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP",
    "EMBEDDING" VECTOR
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE UNIQUE INDEX "VECTOR"."REVIEWS_PK" ON "VECTOR"."REVIEWS" ("ID");

ALTER TABLE VECTOR.REVIEWS ADD CONSTRAINT REVIEWS_PK PRIMARY KEY ( ID ) USING INDEX LOGGING;

DROP TABLE "VECTOR"."REVIEWS_VS";

CREATE TABLE "VECTOR"."REVIEWS_VS" (
    "ID" RAW(16) DEFAULT SYS_GUID(),
    "DOCUMENT_ID" NUMBER,
    "DOCUMENT_NAME" VARCHAR2(512),
    "TEXT" CLOB COLLATE "USING_NLS_COMP",
    "METADATA" CLOB COLLATE "USING_NLS_COMP",
    "EMBEDDING" VECTOR,
    "EMBEDDING_MODEL" VARCHAR2(512)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE INDEX VECTOR.IDX_VS_DOCID ON VECTOR.REVIEWS_VS
    (
     DOCUMENT_ID ASC
    );

CREATE VECTOR INDEX REVIEWS_VS_IVF_IDX ON REVIEWS_VS (EMBEDDING) ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;

CREATE TABLE VECTOR.STOCK (
    REVIEW_ID NUMBER,
    ITEM_NAME VARCHAR2 (512),
    CATEGORY VARCHAR2(4000),
    LOCATION VARCHAR2 (128),
    STOCK INTEGER,
    RESTOCK_DATE DATE
) LOGGING;

ALTER TABLE VECTOR.STOCK ADD CONSTRAINT STOCK_PK PRIMARY KEY ( REVIEW_ID, LOCATION ) USING INDEX LOGGING;

ALTER TABLE VECTOR.STOCK ADD CONSTRAINT REVIEW_ID_FK FOREIGN KEY ( REVIEW_ID ) REFERENCES VECTOR.REVIEWS ( ID ) ON DELETE CASCADE NOT DEFERRABLE NOVALIDATE;

