
DROP TABLE "VECTOR"."REVIEWS";

CREATE TABLE "VECTOR"."REVIEWS" 
   (
    "ID" NUMBER, 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER, 
	"PRICE" NUMBER, 
	"CURRENCY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMBEDDING" VECTOR
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "VECTOR"."REVIEWS_PK" ON "VECTOR"."REVIEWS" ("ID") 
  ;

drop table "VECTOR"."REVIEWS_VS" ;

CREATE TABLE "VECTOR"."REVIEWS_VS" 
   (	
    "ID" RAW(16) DEFAULT SYS_GUID(), 
    "DOCUMENT_ID" NUMBER,
    "DOCUMENT_NAME" VARCHAR2(512),
	"TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"METADATA" CLOB COLLATE "USING_NLS_COMP", 
	"EMBEDDING" VECTOR,
    "EMBEDDING_MODEL" VARCHAR2(512)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;


CREATE INDEX VECTOR.IDX_VS_DOCID ON VECTOR.REVIEWS_VS 
    ( 
     DOCUMENT_ID ASC 
    ) 
;

CREATE VECTOR INDEX reviews_vs_ivf_idx ON reviews_vs (embedding) ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;








